class CfgPatches
{
	class 80s_tanoa_characters_hia
	{
		units[]=
        {
            "80s_tanoa_hia_soldier_base",
            "80s_tanoa_hia_soldier_base_longsleeve",
            "80s_tanoa_hia_rifleman_m16a1",
            "80s_tanoa_hia_rifleman_light_m16a1",
            "80s_tanoa_hia_rifleman_g3a4",
            "80s_tanoa_hia_rifleman_light_g3a4",
            "80s_tanoa_hia_marksman_g3a3",
            "80s_tanoa_hia_sharpshooter_svd",
            "80s_tanoa_hia_autorifleman_mg3",
            "80s_tanoa_hia_autorifleman_assistant_g3a4",
            "80s_tanoa_hia_at_rpg7_g3a4",
            "80s_tanoa_hia_at_assistant_g3a4",
            "80s_tanoa_hia_medic_g3a4",
            "80s_tanoa_hia_hitman_mp5sd3",
            "80s_tanoa_hia_squadlead_m16a1",
            "80s_tanoa_hia_officer_p1",
            "80s_tanoa_hia_crew_mp5",
            "80s_tanoa_hia_pilot_p1",
            "80s_tanoa_hia_motorcycle_scout_m16a1",
            "80s_tanoa_hia_specops_longsleeve_base",
            "80s_tanoa_hia_specops_base",
            "80s_tanoa_hia_specops_rifleman_m16a1",
            "80s_tanoa_hia_specops_marksman_g3a4",
            "80s_tanoa_hia_specops_demolition_mp5sd3",
            "80s_tanoa_hia_specops_at_rpg7_m16a1",
            "80s_tanoa_hia_specops_squadlead_mp5sd3",
            "80s_tanoa_hia_specops_squadlead_m16a1"
        };
		weapons[]=
        {
            "80s_tanoa_hia_uniform_soldier",
            "80s_tanoa_insurgents_ammobearer_akm",
            "80s_tanoa_g3a3_grn_feroz24"
        };
		requiredAddons[]=
		{
            "gm_characters_ge_characters",
			"gm_characters_gc_characters",
			"gm_characters_dk_characters"
		};
	};
};

/////////////////////////
// Uniforms/Weapons     /
/////////////////////////
class CfgWeapons
{
	class gm_ge_army_uniform_soldier_bdu_80_base;
    class gm_ge_army_uniform_soldier_bdu_rolled_80_wdl: gm_ge_army_uniform_soldier_bdu_80_base
    {
        class ItemInfo;
    }
	class 80s_tanoa_hia_uniform_soldier: gm_ge_army_uniform_soldier_bdu_rolled_80_wdl
	{
		scope=2;
        scopeArsenal=2;
		displayName="HIA Uniform (Rolled)";
        picture="\gm\gm_characters\gm_ge_characters\data\ui\picture_gm_ge_uniform_soldier_bdu_rolled_80_wdl_ca";
        class ItemInfo: ItemInfo
        {
            uniformClass="80s_tanoa_hia_soldier_base";
        };
	};
    class 80s_tanoa_hia_uniform_specops: gm_ge_army_uniform_soldier_bdu_rolled_80_wdl
	{
		scope=2;
        scopeArsenal=2;
		displayName="HIA Special Forces (Rolled)";
        picture="\gm\gm_characters\gm_ge_characters\data\ui\picture_gm_ge_uniform_soldier_bdu_rolled_80_wdl_ca";
        class ItemInfo: ItemInfo
        {
            uniformClass="80s_tanoa_hia_specops_base";
        };
	};
    class gm_ge_uniform_soldier_bdu_80_wdl: gm_ge_army_uniform_soldier_bdu_80_base
    {
        class ItemInfo;
    }
    class 80s_tanoa_hia_uniform_soldier_longsleeve: gm_ge_uniform_soldier_bdu_80_wdl
	{
		scope=2;
        scopeArsenal=2;
		displayName="HIA Uniform";
        picture="\gm\gm_characters\gm_ge_characters\data\ui\picture_gm_ge_uniform_soldier_bdu_80_wdl_ca";
        class ItemInfo: ItemInfo
        {
            uniformClass="80s_tanoa_hia_soldier_base_longsleeve";
        };
	};
    class 80s_tanoa_hia_uniform_specops_longsleeve: gm_ge_uniform_soldier_bdu_80_wdl
	{
		scope=2;
        scopeArsenal=2;
		displayName="HIA Special Forces";
        picture="\gm\gm_characters\gm_ge_characters\data\ui\picture_gm_ge_uniform_soldier_bdu_80_wdl_ca";
        class ItemInfo: ItemInfo
        {
            uniformClass="80s_tanoa_hia_specops_longsleeve_base";
        };
	};
    class gm_ge_headgear_hat_boonie_base;
    class 80s_tanoa_hia_specops_boonie: gm_ge_headgear_hat_boonie_base
    {
        displayName="HIA SpecOps Boonie";
        scope=2;
        scopeArsenal=2;
        picture="\gm\gm_characters\gm_ge_characters\data\ui\picture_gm_ge_headgear_hat_boonie_oli_ca";
        hiddenSelectionsTextures[]={"\80s_tanoa\80s_tanoa_vehicles\rfhi\data\80s_tanoa_rfhi_tigerstripe01.paa"};
    };
    class gm_g3a3_grn;
    class 80s_tanoa_g3a3_grn_feroz24: gm_g3a3_grn
    {
        class LinkedItems
        {
            class LinkedItemsOptic
            {
                slot="CowsSlot";
                item="gm_feroz24_blk";
            };
        };
    };
    class gm_m16a1_blk;
    class 80s_tanoa_m16a1_blk_suppressor: gm_m16a1_blk
    {
        scope=1;
        scopeArsenal=1;
        class LinkedItems
        {
            class LinkedItemsMuzzle
            {
                slot = "MuzzleSlot";
                item = "muzzle_snds_M";
            };
        };
    };
};

/////////////////////////
// Units                /
/////////////////////////
class CfgVehicles
{
    //////////////////////////
    // Backpacks            //
    //////////////////////////
    class gm_ge_backpack_satchel_80_san;
    class 80s_tanoa_hia_backpack_satchel_80_san: gm_ge_backpack_satchel_80_san
    {
        scope=1;
        scopeArsenal=1;
        class TransportItems
        {
            class _xx_medikit
            {
                name="gm_ge_army_medkit_80";
                count=1;
            }
            class _xx_burnBandage
            {
                name="gm_ge_army_burnBandage";
                count=2;
            }
            class _xx_gauzeBandage
            {
                name="gm_ge_army_gauzeBandage";
                count=2;
            }
        };
    };
    class gm_dk_army_backpack_73_oli;
    class 80s_tanoa_hia_backpack_mg3_ammo: gm_dk_army_backpack_73_oli
    {
        scope=1;
        scopeArsenal=1;
        class TransportItems
        {
            class _xx_mg3ammo
            {
                name="gm_120rnd_762x51mm_b_t_dm21_mg3_grn";
                count=3;
            }
        }
    }
    class 80s_tanoa_hia_backpack_at: gm_dk_army_backpack_73_oli
    {
        scope=1;
        scopeArsenal=1;
        class TransportItems
        {
            class _xx_rpg7rockets
            {
                name = "gm_1rnd_40mm_heat_pg7v_rpg7";
                count = 3;
            };
        }
    }
    class 80s_tanoa_hia_backpack_demolitions: gm_dk_army_backpack_73_oli
    {
        scope=1;
        scopeArsenal=1;
        class TransportItems
        {
            class _xx_plnpcharge
            {
                name = "gm_explosive_plnp_charge";
                count = 3;
            };
        };
    };
    //////////////////////////
    // Infantry             //
    //////////////////////////
	class gm_ge_army_rifleman_rolled_80_wdl;
    class 80s_tanoa_hia_soldier_base : gm_ge_army_rifleman_rolled_80_wdl
    {
        faction="80s_tanoa_hia";
        displayName="Soldier (Unarmed)";
        uniformClass="80s_tanoa_hia_uniform_soldier";
		serviceBranch="";
		rankInsignias="army_yel";
        faceType="Man_A3";
		side=2;
		genericNames="TanoanMen";
		vehicleClass="Men";
		editorSubcategory="gm_esc_men_80";
        scope=2;
        scopeArsenal=2;
		isgmContent=1;
		dlc="gm";
        author="quarren";
		armbands[]=
		{
			""
		};
		weapons[]=
		{
			"Throw",
			"Put",
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
		};
		Items[]=
		{
			"gm_gc_army_gauzeBandage",
			"gm_gc_army_medkit"
		};
		RespawnItems[]=
		{
			"gm_gc_army_gauzeBandage",
			"gm_gc_army_medkit"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio"
		};
		identityTypes[]=
		{
			"LanguageENGFRE_F",
			"Head_Tanoan",
		};
        hiddenSelectionsTextures[]=
		{
			//"#(rgb,8,8,3)color(0.199,0.230,0.171,1,CO)",
            "\80s_tanoa\80s_tanoa_characters\hia\data\80s_tanoa_bdu_base_co.paa",
            "\80s_tanoa\80s_tanoa_characters\hia\data\80s_tanoa_bdu_overlay_flag.paa"
		};
	};
    class gm_ge_army_rifleman_80_wdl;
    class 80s_tanoa_hia_soldier_base_longsleeve: gm_ge_army_rifleman_80_wdl
    {
        faction="80s_tanoa_hia";
        displayName="Soldier (Longsleeve, Unarmed)";
        uniformClass="80s_tanoa_hia_uniform_soldier_longsleeve";
		serviceBranch="";
		rankInsignias="army_yel";
        faceType="Man_A3";
		side=2;
		genericNames="TanoanMen";
		vehicleClass="Men";
		editorSubcategory="gm_esc_men_80";
        scope=2;
        scopeArsenal=2;
		isgmContent=1;
		dlc="gm";
        author="quarren";
		armbands[]=
		{
			""
		};
		weapons[]=
		{
			"Throw",
			"Put",
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
		};
		Items[]=
		{
			"gm_gc_army_gauzeBandage",
			"gm_gc_army_medkit"
		};
		RespawnItems[]=
		{
			"gm_gc_army_gauzeBandage",
			"gm_gc_army_medkit"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio"
		};
		identityTypes[]=
		{
			"LanguageENGFRE_F",
			"Head_Tanoan",
		};
        hiddenSelectionsTextures[]=
		{
			//"#(rgb,8,8,3)color(0.199,0.230,0.171,1,CO)",
            "\80s_tanoa\80s_tanoa_characters\hia\data\80s_tanoa_bdu_base_co.paa",
            "\80s_tanoa\80s_tanoa_characters\hia\data\80s_tanoa_bdu_overlay_flag.paa"
		};
    };
    class 80s_tanoa_hia_rifleman_m16a1: 80s_tanoa_hia_soldier_base
    {
        displayName="Rifleman (M16A1)";
        scope=2;
		scopeCurator=2;
        role="Rifleman";
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_m16a1_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_m16a1_blk"
		};
		magazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"gm_ge_headgear_m62_net",
			"gm_ge_army_vest_80_rifleman"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"gm_ge_headgear_m62_net",
			"gm_ge_army_vest_80_rifleman"
		};
    };
    class 80s_tanoa_hia_rifleman_light_m16a1: 80s_tanoa_hia_soldier_base
    {
        displayName="Rifleman (Light, M16A1)";
        scope=2;
		scopeCurator=2;
        role="Rifleman";
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_m16a1_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_m16a1_blk"
		};
		magazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"H_Booniehat_oli",
			"gm_ge_army_vest_80_rifleman"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"H_Booniehat_oli",
			"gm_ge_army_vest_80_rifleman"
		};
    };
    class 80s_tanoa_hia_rifleman_g3a4: 80s_tanoa_hia_soldier_base
    {
        displayName="Rifleman (G3A4)";
        scope=2;
		scopeCurator=2;
        role="Rifleman";
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_g3a4_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_g3a4_blk"
		};
		magazines[]=
		{
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"gm_ge_headgear_m62_net",
			"gm_ge_army_vest_80_rifleman"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"gm_ge_headgear_m62_net",
			"gm_ge_army_vest_80_rifleman"
		};
    };
    class 80s_tanoa_hia_rifleman_light_g3a4: 80s_tanoa_hia_soldier_base
    {
        displayName="Rifleman (Light, G3A4)";
        scope=2;
		scopeCurator=2;
        role="Rifleman";
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_g3a4_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_g3a4_blk"
		};
		magazines[]=
		{
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"H_Beret_blk",
			"gm_ge_army_vest_80_rifleman"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"H_Beret_blk",
			"gm_ge_army_vest_80_rifleman"
		};
    };
    class 80s_tanoa_hia_marksman_g3a3: 80s_tanoa_hia_soldier_base
    {
        displayName="Marksman (G3A3)";
        scope=2;
		scopeCurator=2;
        role="Marksman";
        cost=250000;
        textSingular="$STR_A3_nameSound_veh_infantry_sniper_s";
		textPlural="$STR_A3_nameSound_veh_infantry_sniper_p";
        nameSound="veh_infantry_sniper_s";
        class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_sniper_s"
				};
				speechPlural[]=
				{
					"veh_infantry_sniper_p"
				};
			};
		};
        weapons[]=
		{
			"Throw",
			"Put",
			"80s_tanoa_g3a3_grn_feroz24"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"80s_tanoa_g3a3_grn_feroz24"
		};
		magazines[]=
		{
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "H_Beret_blk",
			"gm_ge_army_vest_80_rifleman"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "H_Beret_blk",
			"gm_ge_army_vest_80_rifleman"
		};
    };
    class 80s_tanoa_hia_sharpshooter_svd: 80s_tanoa_hia_soldier_base
    {
        displayName="Sharpshooter (SVD)";
        scope=2;
		scopeCurator=2;
        role="Marksman";
        cost=250000;
        textSingular="$STR_A3_nameSound_veh_infantry_sniper_s";
		textPlural="$STR_A3_nameSound_veh_infantry_sniper_p";
        nameSound="veh_infantry_sniper_s";
        class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_sniper_s"
				};
				speechPlural[]=
				{
					"veh_infantry_sniper_p"
				};
			};
		};
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_svd_wud_pso1"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_svd_wud_pso1"
		};
		magazines[]=
		{
			"gm_10Rnd_762x54mmR_b_t_7t2_svd_blk",
			"gm_10Rnd_762x54mmR_b_t_7t2_svd_blk",
			"gm_10Rnd_762x54mmR_b_t_7t2_svd_blk",
			"gm_10Rnd_762x54mmR_b_t_7t2_svd_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_10Rnd_762x54mmR_b_t_7t2_svd_blk",
			"gm_10Rnd_762x54mmR_b_t_7t2_svd_blk",
			"gm_10Rnd_762x54mmR_b_t_7t2_svd_blk",
			"gm_10Rnd_762x54mmR_b_t_7t2_svd_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "H_Beret_blk",
            "G_Bandanna_aviator",
			"gm_ge_army_vest_80_rifleman"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "H_Beret_blk",
            "G_Bandanna_aviator",
			"gm_ge_army_vest_80_rifleman"
		};
    };
    class 80s_tanoa_hia_autorifleman_mg3: 80s_tanoa_hia_soldier_base
    {
        displayName="Machinegunner (MG3)";
        scope=2;
		scopeCurator=2;
        icon="iconManMG";
        role="MachineGunner";
        textSingular="$STR_A3_nameSound_veh_infantry_MG_s";
		textPlural="$STR_A3_nameSound_veh_infantry_MG_p";
		nameSound="veh_infantry_MG_s";
        class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_MG_s"
				};
				speechPlural[]=
				{
					"veh_infantry_MG_p"
				};
			};
		};
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_mg3_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_mg3_blk"
		};
		magazines[]=
		{
			"gm_120rnd_762x51mm_b_t_dm21_mg3_grn",
			"gm_120rnd_762x51mm_b_t_dm21_mg3_grn",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_120rnd_762x51mm_b_t_dm21_mg3_grn",
			"gm_120rnd_762x51mm_b_t_dm21_mg3_grn",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "gm_ge_headgear_m62",
			"gm_ge_army_vest_80_machinegunner"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "gm_ge_headgear_m62",
			"gm_ge_army_vest_80_machinegunner"
		};
    };
    class 80s_tanoa_hia_autorifleman_assistant_g3a4: 80s_tanoa_hia_soldier_base
    {
        displayName="Machinegunner Assistant (G3A4)";
        scope=2;
		scopeCurator=2;
        role="Rifleman";
        backpack="80s_tanoa_hia_backpack_mg3_ammo";
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_g3a4_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_g3a4_blk"
		};
		magazines[]=
		{
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"gm_ge_headgear_m62",
			"gm_ge_army_vest_80_crew"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"gm_ge_headgear_m62",
			"gm_ge_army_vest_80_crew"
		};
    };
    class 80s_tanoa_hia_at_rpg7_g3a4: 80s_tanoa_hia_soldier_base
    {
        displayName="Anti-Tank (RPG-7&G3A4)";
        scope=2;
		scopeCurator=2;
        icon="iconManAT";
		role="MissileSpecialist";
        backpack="80s_tanoa_hia_backpack_at";
        textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
        class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_AT_s"
				};
				speechPlural[]=
				{
					"veh_infantry_AT_p"
				};
			};
		};
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_g3a4_blk",
            "gm_rpg7_prp"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_g3a4_blk",
            "gm_rpg7_prp"
		};
		magazines[]=
		{
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_1rnd_40mm_heat_pg7v_rpg7",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_1rnd_40mm_heat_pg7v_rpg7",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"gm_ge_headgear_m62",
			"gm_ge_army_vest_80_crew"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"gm_ge_headgear_m62",
			"gm_ge_army_vest_80_crew"
		};
    };
    class 80s_tanoa_hia_at_assistant_g3a4: 80s_tanoa_hia_soldier_base
    {
        displayName="Anti-Tank Assistant (G3A4)";
        scope=2;
		scopeCurator=2;
		role="Rifleman";
        backpack="80s_tanoa_hia_backpack_at";
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_g3a4_blk",
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_g3a4_blk",
		};
		magazines[]=
		{
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
            "gm_20rnd_762x51mm_b_t_dm21_g3_blk",
            "gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
            "gm_20rnd_762x51mm_b_t_dm21_g3_blk",
            "gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"gm_ge_headgear_m62_net",
			"gm_ge_army_vest_80_crew"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"gm_ge_headgear_m62_net",
			"gm_ge_army_vest_80_crew"
		};
    };
    class 80s_tanoa_hia_medic_g3a4: 80s_tanoa_hia_soldier_base
    {
        displayName="Medic (G3A4)";
        scope=2;
		scopeCurator=2;
        icon="iconManMedic";
		role="CombatLifeSaver";
        picture="pictureHeal";
        cost=450000;
        backpack="80s_tanoa_hia_backpack_satchel_80_san";
        textSingular="$STR_A3_nameSound_veh_infantry_medic_s";
		textPlural="$STR_A3_nameSound_veh_infantry_medic_p";
		nameSound="veh_infantry_medic_s";
        class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_medic_s"
				};
				speechPlural[]=
				{
					"veh_infantry_medic_p"
				};
			};
		};
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_g3a4_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_g3a4_blk"
		};
		magazines[]=
		{
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_20rnd_762x51mm_b_t_dm21_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"gm_ge_headgear_m62_net",
			"gm_ge_army_vest_80_rifleman"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
			"gm_ge_headgear_m62_net",
			"gm_ge_army_vest_80_rifleman"
		};
    };
    class 80s_tanoa_hia_hitman_mp5sd3: 80s_tanoa_hia_soldier_base
    {
        displayName="Hitman (MP5SD3)";
        scope=2;
		scopeCurator=2;
        role="Rifleman";
        headgearList[] = {"H_Booniehat_oli", 1, "gm_ge_headgear_hat_boonie_oli", 1};
        class EventHandlers
		{
			init = "if (local (_this select 0)) then {[(_this select 0), [], []] call BIS_fnc_unitHeadgear;};";
		};
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_mp5sd3_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_mp5sd3_blk"
		};
		magazines[]=
		{
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "G_Balaclava_blk",
			"gm_ge_army_vest_80_rifleman"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "G_Balaclava_blk",
			"gm_ge_army_vest_80_rifleman"
		};
    };
    class 80s_tanoa_hia_squadlead_m16a1: 80s_tanoa_hia_soldier_base
    {
        displayName="Squad Leader (M16A1)";
        scope=2;
		scopeCurator=2;
        icon="iconManLeader";
		role="Rifleman";
        textSingular="$STR_A3_nameSound_veh_infantry_officer_s";
		textPlural="$STR_A3_nameSound_veh_infantry_officer_p";
		nameSound="veh_infantry_officer_s";
        class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_officer_s"
				};
				speechPlural[]=
				{
					"veh_infantry_officer_p"
				};
			};
		};
        weapons[]=
		{
			"Throw",
			"Put",
            "Binocular",
			"gm_m16a1_blk",
            "gm_p1_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
            "Binocular",
			"gm_m16a1_blk",
            "gm_p1_blk"
		};
		magazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"gm_ge_headgear_beret_bdx",            
			"gm_ge_army_vest_80_leader"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"gm_ge_headgear_beret_bdx",
			"gm_ge_army_vest_80_leader"
		};
    };
    class 80s_tanoa_hia_officer_p1: 80s_tanoa_hia_soldier_base_longsleeve
    {
        displayName="Officer";
        scope=2;
		scopeCurator=2;
        icon="iconManOfficer";
		role="Officer";
        textSingular="$STR_A3_nameSound_veh_infantry_officer_s";
		textPlural="$STR_A3_nameSound_veh_infantry_officer_p";
		nameSound="veh_infantry_officer_s";
        class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_officer_s"
				};
				speechPlural[]=
				{
					"veh_infantry_officer_p"
				};
			};
		};
        weapons[]=
		{
			"Throw",
			"Put",
            "Binocular",
            "gm_p1_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
            "Binocular",
            "gm_p1_blk"
		};
		magazines[]=
		{
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
            "G_Aviator",
			"gm_ge_headgear_beret_bdx",            
			"gm_ge_army_vest_80_officer"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
            "G_Aviator",
			"gm_ge_headgear_beret_bdx",
			"gm_ge_army_vest_80_officer"
		};
    };
    class 80s_tanoa_hia_crew_mp5: 80s_tanoa_hia_soldier_base_longsleeve
    {
        displayName="Crew (MP5)";
        scope=2;
		scopeCurator=2;
        role="Rifleman";
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_mp5a3_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_mp5a3_blk"
		};
		magazines[]=
		{
            "gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
            "gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "gm_gc_army_headgear_crewhat_80_blk",
			"gm_ge_army_vest_80_crew"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "gm_gc_army_headgear_crewhat_80_blk",
			"gm_ge_army_vest_80_crew"
		};
    };
    class 80s_tanoa_hia_pilot_p1: 80s_tanoa_hia_soldier_base_longsleeve
    {
        displayName="Pilot (P1)";
        scope=2;
		scopeCurator=2;
        role="Rifleman";
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_p1_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_p1_blk"
		};
		magazines[]=
		{
			"gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "G_Aviator",
            "gm_ge_headgear_sph4_oli",
			"gm_ge_army_vest_80_officer"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "G_Aviator",
            "gm_ge_headgear_sph4_oli",
			"gm_ge_army_vest_80_officer"
		};
    };
    class 80s_tanoa_hia_motorcycle_scout_m16a1: 80s_tanoa_hia_soldier_base
    {
        displayName="Motorcycle Scout (M16A1)";
        scope=2;
		scopeCurator=2;
        role="Rifleman";
        backpack="gm_dk_army_backpack_73_oli";
        weapons[]=
		{
			"Throw",
			"Put",
            "gm_df7x40_grn",
			"gm_m16a1_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
            "gm_df7x40_grn",
			"gm_m16a1_blk"
		};
		magazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "G_Aviator",
			"gm_gc_headgear_fjh_model4_wht",
			"gm_ge_army_vest_80_crew"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"ItemWatch",
            "G_Aviator",
			"gm_gc_headgear_fjh_model4_wht",
			"gm_ge_army_vest_80_crew"
		};
    };
    // SpecOps
    class 80s_tanoa_hia_specops_base : gm_ge_army_rifleman_rolled_80_wdl
    {
        faction="80s_tanoa_hia";
        displayName="Special Forces (Unarmed)";
        uniformClass="80s_tanoa_hia_uniform_specops";
		serviceBranch="";
		rankInsignias="army_yel";
        faceType="Man_A3";
		side=2;
		genericNames="TanoanMen";
		vehicleClass="Men";
		editorSubcategory="gm_esc_men_special_80";
        scope=2;
        scopeArsenal=2;
		isgmContent=1;
		dlc="gm";
        author="quarren";
		armbands[]=
		{
			""
		};
		weapons[]=
		{
			"Throw",
			"Put",
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
		};
		Items[]=
		{
			"gm_gc_army_gauzeBandage",
			"gm_gc_army_medkit"
		};
		RespawnItems[]=
		{
			"gm_gc_army_gauzeBandage",
			"gm_gc_army_medkit"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio"
		};
		identityTypes[]=
		{
			"LanguageENGFRE_F",
			"Head_Tanoan",
		};
        hiddenSelectionsTextures[]=
		{
			//"#(rgb,8,8,3)color(0.199,0.230,0.171,1,CO)",
            "\80s_tanoa\80s_tanoa_characters\hia\data\80s_tanoa_bdu_base_tigerstripe_co.paa",
            "\80s_tanoa\80s_tanoa_characters\hia\data\80s_tanoa_bdu_overlay_flag.paa"
		};
	};
    class 80s_tanoa_hia_specops_longsleeve_base: gm_ge_army_rifleman_80_wdl
    {
        faction="80s_tanoa_hia";
        displayName="Special Forces (Longsleeve, Unarmed)";
        uniformClass="80s_tanoa_hia_uniform_specops_longsleeve";
		serviceBranch="";
		rankInsignias="army_yel";
        faceType="Man_A3";
		side=2;
		genericNames="TanoanMen";
		vehicleClass="Men";
		editorSubcategory="gm_esc_men_special_80";
        scope=2;
        scopeArsenal=2;
		isgmContent=1;
		dlc="gm";
        author="quarren";
		armbands[]=
		{
			""
		};
		weapons[]=
		{
			"Throw",
			"Put",
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
		};
		Items[]=
		{
			"gm_gc_army_gauzeBandage",
			"gm_gc_army_medkit"
		};
		RespawnItems[]=
		{
			"gm_gc_army_gauzeBandage",
			"gm_gc_army_medkit"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio"
		};
		identityTypes[]=
		{
			"LanguageENGFRE_F",
			"Head_Tanoan",
		};
        hiddenSelectionsTextures[]=
		{
			//"#(rgb,8,8,3)color(0.199,0.230,0.171,1,CO)",
            "\80s_tanoa\80s_tanoa_characters\hia\data\80s_tanoa_bdu_base_tigerstripe_co.paa",
            "\80s_tanoa\80s_tanoa_characters\hia\data\80s_tanoa_bdu_overlay_flag.paa"
		};
    };
    class 80s_tanoa_hia_specops_rifleman_m16a1: 80s_tanoa_hia_specops_longsleeve_base
    {
        displayName="Rifleman (M16A1)";
        scope=2;
		scopeCurator=2;
        icon="iconMan";
		role="Rifleman";
        backpack="gm_dk_army_backpack_73_oli";
        weapons[]=
		{
			"Throw",
			"Put",
			"80s_tanoa_m16a1_blk_suppressor"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"80s_tanoa_m16a1_blk_suppressor"
		};
		magazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"80s_tanoa_hia_specops_boonie",
            "G_Bandanna_blk",
			"gm_ge_army_vest_80_crew"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"80s_tanoa_hia_specops_boonie",
            "G_Bandanna_blk",
			"gm_ge_army_vest_80_crew"
		};
    };
    class 80s_tanoa_hia_specops_marksman_g3a4: 80s_tanoa_hia_specops_longsleeve_base
    {
        displayName="Marksman (G3A3)";
        scope=2;
		scopeCurator=2;
        role="Marksman";
        cost=250000;
        textSingular="$STR_A3_nameSound_veh_infantry_sniper_s";
		textPlural="$STR_A3_nameSound_veh_infantry_sniper_p";
        nameSound="veh_infantry_sniper_s";
        backpack="gm_dk_army_backpack_73_oli";
        class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_sniper_s"
				};
				speechPlural[]=
				{
					"veh_infantry_sniper_p"
				};
			};
		};
        weapons[]=
		{
			"Throw",
			"Put",
			"80s_tanoa_g3a3_grn_feroz24"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"80s_tanoa_g3a3_grn_feroz24"
		};
		magazines[]=
		{
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_20Rnd_762x51mm_b_DM41_g3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"80s_tanoa_hia_specops_boonie",
            "G_Bandanna_aviator",
			"gm_ge_army_vest_80_crew"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"80s_tanoa_hia_specops_boonie",
            "G_Bandanna_aviator",
			"gm_ge_army_vest_80_crew"
		};
    };
    class 80s_tanoa_hia_specops_at_rpg7_m16a1: 80s_tanoa_hia_specops_longsleeve_base
    {
        displayName="Anti-Tank (RPG-7)";
        scope=2;
		scopeCurator=2;
        icon="iconManAT";
		role="MissileSpecialist";
        backpack="80s_tanoa_hia_backpack_at";
        textSingular="$STR_A3_nameSound_veh_infantry_AT_s";
		textPlural="$STR_A3_nameSound_veh_infantry_AT_p";
		nameSound="veh_infantry_AT_s";
        class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_AT_s"
				};
				speechPlural[]=
				{
					"veh_infantry_AT_p"
				};
			};
		};
        weapons[]=
		{
			"Throw",
			"Put",
			"80s_tanoa_m16a1_blk_suppressor",
            "gm_rpg7_prp"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"80s_tanoa_m16a1_blk_suppressor",
            "gm_rpg7_prp"
		};
		magazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_1rnd_40mm_heat_pg7v_rpg7",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_1rnd_40mm_heat_pg7v_rpg7",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"gm_ge_headgear_hat_beanie_blk",
            "G_Bandanna_blk",
			"gm_ge_army_vest_80_crew"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"gm_ge_headgear_hat_beanie_blk",
            "G_Bandanna_blk",
			"gm_ge_army_vest_80_crew"
		};
        identityTypes[]=
		{
			"LanguageENGFRE_F",
			"Head_NATO"
		};
    };
    class 80s_tanoa_hia_specops_demolition_mp5sd3: 80s_tanoa_hia_specops_longsleeve_base
    {
        displayName="Demolition (MP5SD3)";
        scope=2;
		scopeCurator=2;
        Icon="iconManExplosive";
		role="Sapper";
		picture="pictureExplosive";
		cost=115000;
		canDeactivateMines=1;
        backpack="80s_tanoa_hia_backpack_demolitions";
        weapons[]=
		{
			"Throw",
			"Put",
			"gm_mp5sd3_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
			"gm_mp5sd3_blk"
		};
		magazines[]=
		{
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
            "gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
            "gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
            "gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
            "gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"gm_ge_headgear_beret_crew_blk",
            "G_Bandanna_oli",
			"gm_ge_army_vest_80_demolition"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"gm_ge_headgear_beret_crew_blk",
            "G_Bandanna_oli",
			"gm_ge_army_vest_80_demolition"
		};
    };
    class 80s_tanoa_hia_specops_squadlead_mp5sd3: 80s_tanoa_hia_specops_longsleeve_base
    {
        displayName="Squad Leader (MP5SD3)";
        scope=2;
		scopeCurator=2;
        icon="iconManLeader";
		role="Rifleman";
        textSingular="$STR_A3_nameSound_veh_infantry_officer_s";
		textPlural="$STR_A3_nameSound_veh_infantry_officer_p";
		nameSound="veh_infantry_officer_s";
        class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_officer_s"
				};
				speechPlural[]=
				{
					"veh_infantry_officer_p"
				};
			};
		};
        backpack="gm_dk_army_backpack_73_oli";
        weapons[]=
		{
			"Throw",
			"Put",
            "Binocular",
			"gm_mp5sd3_blk_feroz24",
            "gm_p1_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
            "Binocular",
			"gm_mp5sd3_blk_feroz24",
            "gm_p1_blk"
		};
		magazines[]=
		{
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
            "gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
            "gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
			"gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
            "gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
            "gm_30rnd_9x19mm_b_dm51_mp5a3_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"gm_ge_headgear_beret_blk",
            "G_Bandanna_oli",
			"gm_ge_army_vest_80_leader"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"gm_ge_headgear_beret_blk",
            "G_Bandanna_oli",
			"gm_ge_army_vest_80_leader"
		};
    };
    class 80s_tanoa_hia_specops_squadlead_m16a1: 80s_tanoa_hia_specops_longsleeve_base
    {
        displayName="Squad Leader (M16A1)";
        scope=2;
		scopeCurator=2;
        icon="iconManLeader";
		role="Rifleman";
        textSingular="$STR_A3_nameSound_veh_infantry_officer_s";
		textPlural="$STR_A3_nameSound_veh_infantry_officer_p";
		nameSound="veh_infantry_officer_s";
        class SpeechVariants
		{
			class Default
			{
				speechSingular[]=
				{
					"veh_infantry_officer_s"
				};
				speechPlural[]=
				{
					"veh_infantry_officer_p"
				};
			};
		};
        backpack="gm_dk_army_backpack_73_oli";
        weapons[]=
		{
			"Throw",
			"Put",
            "Binocular",
			"80s_tanoa_m16a1_blk_suppressor",
            "gm_p1_blk"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put",
            "Binocular",
			"80s_tanoa_m16a1_blk_suppressor",
            "gm_p1_blk"
		};
		magazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		respawnMagazines[]=
		{
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
			"gm_30Rnd_556x45mm_B_M855_stanag_gry",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
            "gm_8rnd_9x19mm_b_dm11_p1_blk",
			"gm_handGrenade_frag_rgd5",
			"gm_handGrenade_frag_rgd5"
		};
		linkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"gm_ge_headgear_beret_blk",
            "G_Bandanna_oli",
			"gm_ge_army_vest_80_leader"
		};
		respawnLinkedItems[]=
		{
			"gm_gc_compass_f73",
			"ItemRadio",
			"itemMap",
			"gm_watch_kosei_80",
			"gm_ge_headgear_beret_blk",
            "G_Bandanna_oli",
			"gm_ge_army_vest_80_leader"
		};
    };
};
// CfgGroups
class CfgGroups
{
	class Indep
	{
		class 80s_tanoa_hia
		{
			name="Horizon Islands Army (80s)";
			class gm_infantry
			{
				name="Infantry";
				class 80s_tanoa_hia_infantry_squad
				{
					name="Infantry Squad";
					side=2;
					faction="80s_tanoa_hia";
					icon="\A3\ui_f\data\map\markers\nato\b_inf.paa";
					class Leader1
					{
						side=2;
						vehicle="80s_tanoa_hia_squadlead_m16a1";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class MG1: Leader1
					{
						vehicle="80s_tanoa_hia_autorifleman_mg3";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class MG2: MG1
					{
						vehicle="80s_tanoa_hia_autorifleman_assistant_g3a4";
						rank="PRIVATE";
						position[]={-5,-5,0};
					};
					class AT1: MG1
					{
						vehicle="80s_tanoa_hia_at_rpg7_g3a4";
						position[]={10,-10,0};
					};
					class AT2: AT1
					{
						vehicle="80s_tanoa_hia_at_assistant_g3a4";
						rank="PRIVATE";
						position[]={-10,-10,0};
					};
					class Rifleman1: MG1
					{
						vehicle="80s_tanoa_hia_medic_g3a4";
						rank="CORPORAL";
						position[]={15,-15,0};
					};
					class Rifleman2: Rifleman1
					{
						vehicle="80s_tanoa_hia_marksman_g3a3";
						rank="PRIVATE";
						position[]={-15,-15,0};
					};
					class Rifleman3: Rifleman2
					{
                        vehicle="80s_tanoa_hia_rifleman_m16a1";
                        rank="PRIVATE";
						position[]={20,-20,0};
					};
				};
                class 80s_tanoa_hia_infantry_fireteam_light
				{
					name="Fire Team (Light)";
					side=2;
					faction="80s_tanoa_hia";
					icon="\A3\ui_f\data\map\markers\nato\b_inf.paa";
					class Leader1
					{
						side=2;
						vehicle="80s_tanoa_hia_squadlead_m16a1";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Rifleman1: Leader1
					{
						vehicle="80s_tanoa_hia_rifleman_light_m16a1";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class Rifleman2: Rifleman1
					{
						vehicle="80s_tanoa_hia_rifleman_light_g3a4";
						rank="PRIVATE";
						position[]={-5,-5,0};
					};
					class Marksman: Rifleman1
					{
						vehicle="80s_tanoa_hia_marksman_g3a3";
						position[]={10,-10,0};
					};
				};
                class 80s_tanoa_hia_infantry_mggroup
				{
					name="MG Team";
					side=2;
					faction="80s_tanoa_hia";
					icon="\A3\ui_f\data\map\markers\nato\b_inf.paa";
					class Leader1
					{
						side=2;
						vehicle="80s_tanoa_hia_squadlead_m16a1";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class MG1: Leader1
					{
						vehicle="80s_tanoa_hia_autorifleman_mg3";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class MG2: MG1
					{
						vehicle="80s_tanoa_hia_autorifleman_assistant_g3a4";
						rank="PRIVATE";
						position[]={-5,-5,0};
					};
				};
                class 80s_tanoa_hia_infantry_atgroup
				{
					name="AT Team";
					side=2;
					faction="80s_tanoa_hia";
					icon="\A3\ui_f\data\map\markers\nato\b_inf.paa";
					class Leader1
					{
						side=2;
						vehicle="80s_tanoa_hia_squadlead_m16a1";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class MG1: Leader1
					{
						vehicle="80s_tanoa_hia_at_rpg7_g3a4";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class MG2: MG1
					{
						vehicle="80s_tanoa_hia_at_assistant_g3a4";
						rank="PRIVATE";
						position[]={-5,-5,0};
					};
				};
                class 80s_tanoa_hia_infantry_sharpshooter_sentry
				{
					name="Sharpshooter Sentry";
					side=2;
					faction="80s_tanoa_hia";
					icon="\A3\ui_f\data\map\markers\nato\b_recon.paa";
					class Sharpshooter
					{
						side=2;
						vehicle="80s_tanoa_hia_sharpshooter_svd";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Spotter: Sharpshooter
					{
						vehicle="80s_tanoa_hia_rifleman_g3a4";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
				};
                // SpecOps
                class 80s_tanoa_hia_specops_team_demolitions
				{
					name="SpecOps Team (Demolition)";
					side=2;
					faction="80s_tanoa_hia";
					icon="\A3\ui_f\data\map\markers\nato\b_inf.paa";
					class Leader1
					{
						side=2;
						vehicle="80s_tanoa_hia_specops_squadlead_mp5sd3";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Rifleman1: Leader1
					{
						vehicle="80s_tanoa_hia_specops_demolition_mp5sd3";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class Rifleman2: Rifleman1
					{
						vehicle="80s_tanoa_hia_specops_rifleman_m16a1";
						rank="PRIVATE";
						position[]={-5,-5,0};
					};
					class Marksman: Rifleman1
					{
						vehicle="80s_tanoa_hia_specops_marksman_g3a4";
						position[]={10,-10,0};
					};
				};
                class 80s_tanoa_hia_specops_team_at
				{
					name="SpecOps Team (Anti-Tank)";
					side=2;
					faction="80s_tanoa_hia";
					icon="\A3\ui_f\data\map\markers\nato\b_inf.paa";
					class Leader1
					{
						side=2;
						vehicle="80s_tanoa_hia_specops_squadlead_mp5sd3";
						rank="SERGEANT";
						position[]={0,0,0};
					};
					class Rifleman1: Leader1
					{
						vehicle="80s_tanoa_hia_specops_at_rpg7_m16a1";
						rank="CORPORAL";
						position[]={5,-5,0};
					};
					class Rifleman2: Rifleman1
					{
						vehicle="80s_tanoa_hia_specops_rifleman_m16a1";
						rank="PRIVATE";
						position[]={-5,-5,0};
					};
					class Marksman: Rifleman1
					{
						vehicle="80s_tanoa_hia_specops_marksman_g3a4";
						position[]={10,-10,0};
					};
				};
			};
		};
	};
};